tosca_definitions_version: tosca_simple_yaml_1_0

metadata:
  template_name: GcCloudProvider
  template_author: yaniv.k
  template_version: 0.1.0
  template_icon: shell-icon.png

description: >
  sample deployment path file

imports:
  - cloudshell_standard: cloudshell_cloud_provider_standard_1_0_0.yaml

node_types:

  vendor.resource.Google Cloud VM from Template:
    description: Create a single VM instance from an existing template
    derived_from: cloudshell.nodes.CustomDeploymentOption
    properties:
      Template Name:
        type: string
        description: 'The name of the template that should be used'
        default: ''
        tags: [user_input] # editable_only_in_app_template

    artifacts:
      icon:
        file: shell-icon.png
        type: tosca.artifacts.File
